# Describes the format for available Niko Home Control II services
set_light_brightness:
  name: Set brightness for light
  description: Sets the brightness for a light.
  target:
    entity:
      domain: light
  fields:
    light_brightness:
      name: Brightness
      description: The brightness as a percentage.
      required: true
      selector:
        number:
          min: 0
          max: 100
set_light_color:
  name: Set color for light
  description: Sets the color for a light.
  target:
    entity:
      domain: light
  fields:
    light_color:
      name: Color
      description: The color
      required: true
      selector:
        color_rgb: